before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y rabbitmq-server"

before_script:
  "rake vendor && rake codegen:ffi"
script:
  "sudo /usr/sbin/rabbitmq-server -detached && sleep 10 && rake"
after_script:
  "rake install"

language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6

notifications:
  email: false
